name: Maven Build

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean install

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

   - name: Copy file to S3 bucket
      run: |
        aws s3 cp target/config-server-0.0.1-SNAPSHOT.jar s3://yletter-artifacts/config-server.jar
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # Replace with your AWS region